PRODUCT_VERSION_MAJOR = 20
PRODUCT_VERSION_MINOR = 0
PRODUCT_EXODUS_VERSION = mouse
PRODUCT_VERSION_ANDROID = 13

# Internal version
LINEAGE_VERSION := ExodusOS-$(PRODUCT_VERSION_ANDROID)-$(shell date +%Y%m%d)-$(LINEAGE_BUILD)-$(PRODUCT_EXODUS_VERSION)

# Display version
LINEAGE_DISPLAY_VERSION := ExodusOS-$(PRODUCT_VERSION_ANDROID)-$(LINEAGE_BUILD)-$(PRODUCT_EXODUS_VERSION)
